### ISSUE TITLE
Can't book against unknown entity

### ISSUE THREAD

**Issue by kefcom** [Brixel/HaSpMan#45]
I can't make a transaction with an unknown entity:
No error message, just a crash.
![afbeelding](https://user-images.githubusercontent.com/6786386/148545044-c642ecb2-2587-4ce7-a6bb-422c90134f56.png)

**Comment by Joren-Thijs** [comment]
Thes seems to already be fixed in MudBlazor 6. Plz test again.

**Comment by BerendWouters** [comment]
Issue is still occurring. Reproducable path:
1. Open a transaction (new or edit, doesn't matter)
2. Try to add a new "non-member" by just entering it's name and then entering.
3. Enter causes the form to save.

**Comment by kefcom** [comment]
Still not fixed in 0.26.1

**Comment by Kenny-Lacroix** [comment]
still not fixed 0.33.8 :)
